### ISSUE TITLE
Connections lost

### ISSUE THREAD

**Issue by jjtbsomhorst** [jordenc/com.onkyo#1]
**What is your version (Settings → System)?**

latest from store

**What did you try to achieve?**

Give my Onkyo commands after a power cycle

**What was the result?**

Onkyo didn't react

**What did you expect as result?**

Onkyo would react

**Any other remarks**

Currently the app loses connection whenever I power down my Onkyo. After that the app does not reconnect anymore leaving it useless until I restart Homey. It would be a very nice to the app try to reconnect every x minutes / seconds after the connection has been losts

**Comment by epjjansen** [comment]
Which Onkyo do you have?
You need to keep the power on the Network part or else you cannot cycle the power from the Onkyo

Network Standby

■Default Value : Off

You can turn on the power of the unit via network using an application such as Onkyo Remote.

"On": Use this function

"Off": Do not use this function

•When "Network Standby" is used, the power consumption increases even when the unit is on standby. However, the increase in power consumption is kept to a minimum by automatically entering the HYBRID STANDBY mode, where only the essential circuit is operating.

**Comment by epjjansen** [comment]
@jjtbsomhorst Did you test this with the Network Standby function?

**Comment by jordenc** [comment]
Better late than never:
I bought a Denon to replace my Onkyo. My Onkyo is now disconnected. Will bring it to the office so I can easily experiment with it, pulling the plug etc. to see if I can make this work.

I will make a SDKv2 version before I sell my Onkyo.

**Comment by jordenc** [comment]
Still not able to detect that the connection broke down, I think that is not the way to go.

So I thought; why don't I make a "Disconnect & Reconnect" card so you can do this from within Homey?
I will create this today and it will be released in version 2.0.0

**Comment by jjtbsomhorst** [comment]
sorry for the extremely late response. My Onkyo is a TX-NR646

**Comment by jordenc** [comment]
The TX-NR646 is the same as I developed the app on.

There is no way I can detect that the connection is down, but as of 2.0.0 there is a flowcard that you can use to disconnect & reconnect to the Onkyo.
