### ISSUE TITLE
Install problems homey 2

### ISSUE THREAD

**Issue by gerrit1968** [jordenc/com.onkyo#16]
Hello i am running on this moment version 2 experimental, but i cant install the app
Do you have a experience with this

![32b88a2d-2c3a-4910-87e2-7b7c0a82e3be](https://user-images.githubusercontent.com/45800615/49825132-f9e6dd80-fd83-11e8-8022-56d6bc197f37.png)

**Comment by jordenc** [comment]
I made a mistake in the compatibility version. Will release an update to the app store (2.0.4) but it might take a few days before it is published.

**Comment by gerrit1968** [comment]
Thank you very much 😀

**Comment by jordenc** [comment]
The app store has been updated with 2.0.4 now :)
