### ISSUE TITLE
Can not discover Onkyo with dynamic IP

### ISSUE THREAD

**Issue by jjtbsomhorst** [jordenc/com.onkyo#2]
**What is you  version (Settings → System)?**

latest store version

**What did you try to achieve?**

Add onkyo with dynamic IP address

**What was the result?**
Only possible to add static IP adres in settings

**What did you expect as result?**

I would have an option to 'discover'  the onkyo

**Any other remarks**

Currently it isn't possible to let the app discover an onkyo device. In the mobile app (from onkyo) the app will try to discover a device everytime you start it. I would like to have this option also in the Homey app. I think this can be build together with the reconnect issue.

**Comment by jjtbsomhorst** [comment]
I just found an nodejs library  you could use maybe. https://github.com/tillbaks/node-eiscp/. This library also has auto discover etc.

**Comment by jordenc** [comment]
I wrote this app with the idea in mind that some people might have multiple Onkyo's. If I use discovery, it is hard to make sure the right one is selected. I have one Onkyo so it's also hard to test if I can make it work dynamicly.

It's probably a better plan to make it a static IP in your router.

**Comment by jjtbsomhorst** [comment]
Thanks for the update. I have given the device a static ip adres now and it seems to be working now.
