### ISSUE TITLE
Feature: Support for 3rd zone

### ISSUE THREAD

**Issue by mrtexmex** [jordenc/com.onkyo#7]
It would be really nice if the app supported a third zone instead of just two, since some TX-NR receivers support three zones (for example TX-NR3007). 

(We communicated about this at the Homey Apps page, but since the comments page there has been removed I put the request here as well just as a kind reminder.)

Many thanks in advance!

**Comment by jordenc** [comment]
This should be available in version 2.0.0 which I am publishing within a few days.

**Comment by jordenc** [comment]
I will close this issue for now, feel free to reopen if it doesn't work on 2.0.0
