### ISSUE TITLE
Input selection TV/Tape not working

### ISSUE THREAD

**Issue by Vincent75b** [jordenc/com.onkyo#8]
Great plug-in, Thanks! All other inputs are working, except this one :-(  Both in controlling (from devices) as in flows...

**Comment by Vincent75b** [comment]
I have a TX-8270 btw

**Comment by jordenc** [comment]
This should be available in version 2.0.0 which I am publishing within a few days. I will close this issue for now, feel free to reopen if it doesn't work on 2.0.0
