### ISSUE TITLE
Pioneer VSX 932 uses the Onkyo ISCP to control your receiver. How to add to homey

### ISSUE THREAD

**Issue by Roppieee** [jordenc/com.onkyo#9]
Hi,

I bought the pioneer VSX 932 recently but unfortunately it is not using telnet anymore but pioneer changed to Onkyo ISCP protocol. For this reason I assume I should be able to control the receiver through homey with the Onkyo app instead of the Pioneer app. Unfortunately when I try to add the pioneer receiver through the Onkyo App, it is not recognised. Could you please add the Pioneer VSX 932 to this app?

Thanks

**Comment by jordenc** [comment]
This should be available in version 2.0.0 which I am publishing within a few days. I will close this issue for now, feel free to reopen if it doesn't work on 2.0.0
